version: '3.5'

services:
  users-ms:
    container_name: users-ms
    build: 
      context: ../.
      dockerfile: ./src/services/users/docker/Dockerfile
    ports:
      - 4500:4500
    environment:
      REDIS_URL: redis://redis:6379
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      KAFKA_URL: kafka:9092
      USERS_APP_PORT: 4500
    networks:
      - my-forum

  posts-ms:
    container_name: posts-ms
    build: 
      context: ../.
      dockerfile: ./src/services/posts/docker/Dockerfile
    ports:
      - 4000:4000
    environment:
      REDIS_URL: redis://redis:6379
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      KAFKA_URL: kafka:9092
      POSTS_APP_PORT: 4000
    networks:
      - my-forum
    depends_on:
      - users-ms

  notifications-ms:
    container_name: notifications-ms
    build: 
      context: ../.
      dockerfile: ./src/services/notifications/docker/Dockerfile
    ports:
      - 4700:4700
    environment:
      REDIS_URL: redis://redis:6379
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      KAFKA_URL: kafka:9092
      NOTIFICATIONS_APP_PORT: 4700
    networks:
      - my-forum
    depends_on:
      - users-ms

  api-gateway:
    container_name: api-gateway
    build: 
      context: ../.
      dockerfile: ./src/api-gateway/docker/Dockerfile
    ports:
      - 7500:7500
    environment:
      REDIS_URL: redis://redis:6379
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      KAFKA_URL: kafka:9092
      API_GATEWAY_APP_PORT: 7500
      POSTS_MS_URL: http://posts-ms:4000
      USERS_MS_URL: http://users-ms:4500
    networks:
      - my-forum
    depends_on:
      - users-ms
      - posts-ms
      - notifications-ms

networks:
  my-forum:
